services:
  - type: web
    name: kream-auth-server
    env: python
    plan: free
    buildCommand: pip install -r kream-auth-server/requirements.txt
    startCommand: "gunicorn -b 0.0.0.0:10000 kream-auth-server/server_project.server:app"
    envVars:
      - key: PORT
        value: 10000
